### ISSUE TITLE
nested parameters

### ISSUE THREAD

**Issue by ahoarau** [cbandera/rosparam_handler#54]
It would be awesome if we could do : 
```yml
some_group:
   a_param: 0
   b_param: 0
some_other_group:
   a_param: 0
   b_param: 0
   c_param: 0
```
I though it was the purpose of 'groups', but it's only a dynamic reconfigure goodie.

**Comment by artivis** [comment]
Hi, thanks for the comment. What would you expect `some_group` to be ? A nested namespace ?
Cheers.

**Comment by ahoarau** [comment]
Yes exactly. Practical example : a pid controller. The param yaml would be something like : 
```yaml
controller_name : test
some_other_param : 2
pid:
    p: [ 1, 2, 3 ]
    i:  [ 1, 2, 3 ]
    d: [ 1, 2, 3 ]
```
But for that I would have to define a config for each 'level' ( the level that contains controller_name and some_other_param and another for the pid alone)
